export const NAME_FORMAT = /^[a-zA-Z]+$/;
export const PASSWORD_FORMAT =
  /(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]+/;
export const PHONE_FORMAT = /^\d{10}$/;
export const EMAIL_FORMAT = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export const USER_NAME_MIN_LENGTH = 3;
export const USER_NAME_MAX_LENGTH = 30;
export const PHONE_DIGITS_LENGTH = 10;
export const PASSWORD_MIN_LENGTH = 8;
export const PASSWORD_MAX_LENGTH = 30;
export const FIRST_NAME_MIN_LENGTH = 1;
export const FIRST_NAME_MAX_LENGTH = 30;
export const LAST_NAME_MIN_LENGTH = 1;
export const LAST_NAME_MAX_LENGTH = 30;
export const MIN_TITLE_LENGTH = 3;
export const MAX_TITLE_LENGTH = 30;
export const MIN_DESCRIPTION_LENGTH = 0;
export const MAX_DESCRIPTION_LENGTH = 500;
export const LIGHT_THEME = "autumn";
export const DARK_THEME = "coffee";
export const EVENT_COVER_BY_DEFAULT = "https://images.pexels.com/photos/431722/pexels-photo-431722.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1";
